---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-controller
  namespace: syncer-service
  labels:
    app: workload-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-controller
  template:
    metadata:
      labels:
        app: workload-controller
    spec:
      serviceAccountName: workload-controller
      containers:
        - name: controller
          image: zakisk/secret-service:latest
          imagePullPolicy: Always
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability
            - name: METRICS_DOMAIN
              value: kueue.x-k8s.io/secret-service
            - name: KUEUE_NAMESPACE
              value: kueue-system
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
